CREATE TABLE IF NOT EXISTS chain_activity (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    title VARCHAR(200) NOT NULL COMMENT '接龙活动主题',
    theme VARCHAR(500) COMMENT '主题说明（供二次创作参考）',
    description TEXT COMMENT '活动介绍',
    rules TEXT COMMENT '参与规则',
    cover_image VARCHAR(255) COMMENT '活动封面图',
    banner_image VARCHAR(255) COMMENT '活动Banner图',
    seed_work_id BIGINT COMMENT '种子作品ID（接龙起点作品）',
    category_id BIGINT COMMENT '关联分类ID',
    start_time DATETIME NOT NULL COMMENT '活动开始时间',
    end_time DATETIME NOT NULL COMMENT '活动结束时间',
    max_chain_depth INT DEFAULT 0 COMMENT '最大接龙深度（0表示不限制）',
    work_count INT DEFAULT 0 COMMENT '接龙作品总数',
    participant_count INT DEFAULT 0 COMMENT '参与人数',
    view_count INT DEFAULT 0 COMMENT '浏览量',
    status TINYINT DEFAULT 1 COMMENT '状态 0:关闭 1:开启',
    create_by BIGINT COMMENT '创建人ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记 0:未删除 1:已删除',
    INDEX idx_status (status),
    INDEX idx_start_time (start_time),
    INDEX idx_end_time (end_time),
    INDEX idx_create_time (create_time),
    INDEX idx_seed_work_id (seed_work_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='手作接龙活动表';

CREATE TABLE IF NOT EXISTS chain_work (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    chain_activity_id BIGINT NOT NULL COMMENT '接龙活动ID',
    work_id BIGINT NOT NULL COMMENT '作品ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    parent_chain_work_id BIGINT COMMENT '父接龙作品ID（灵感来源）',
    root_chain_work_id BIGINT COMMENT '根接龙作品ID（种子作品）',
    inspiration_remark VARCHAR(500) COMMENT '灵感说明（如何基于原作创作）',
    chain_level INT DEFAULT 1 COMMENT '接龙层级（种子为1）',
    branch_count INT DEFAULT 0 COMMENT '子分支数量',
    like_count INT DEFAULT 0 COMMENT '点赞数',
    submit_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '投稿时间',
    audit_status TINYINT DEFAULT 1 COMMENT '审核状态 0:待审核 1:已通过 2:已拒绝',
    audit_remark VARCHAR(500) COMMENT '审核备注',
    auditor_id BIGINT COMMENT '审核人ID',
    audit_time DATETIME COMMENT '审核时间',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记 0:未删除 1:已删除',
    UNIQUE KEY uk_chain_work (chain_activity_id, work_id),
    INDEX idx_chain_activity_id (chain_activity_id),
    INDEX idx_work_id (work_id),
    INDEX idx_user_id (user_id),
    INDEX idx_parent_chain_work_id (parent_chain_work_id),
    INDEX idx_root_chain_work_id (root_chain_work_id),
    INDEX idx_submit_time (submit_time),
    INDEX idx_chain_level (chain_level),
    INDEX idx_audit_status (audit_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='接龙作品表';
